sudo: required
services: 
  - docker

before_install:
  - docker build -t jyotiprasad5/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true jyotiprasad5/docker-react npm run test